In [25]:
import pandas as pd 
import numpy as np

In [26]:
net2 = pd.read_csv("predictions2.csv")
net3 = pd.read_csv("predictions3.csv")
net4 = pd.read_csv("predictions4.csv")
net5 = pd.read_csv("predictions5.csv")
net6 = pd.read_csv("predictions6.csv")
svr = pd.read_csv("predictions_svr.csv")
svr2 = pd.read_csv("predictions_svr2.csv")
gbm = pd.read_csv("predictions7.csv")
rf = pd.read_csv("predictions_rf.csv")

In [27]:
net2["y2"] = net3["y"]
net2["y3"] = net4["y"]
net2["y4"] = svr["y"]
net2["y5"] = svr2["y"]
net2["y6"] = net5["y"]
net2["y7"] = net6["y"]
net2["y8"] = gbm["y"]
net2["y9"] = rf["y"]

In [28]:
preds= net2.copy()
preds["y"]= net2[[ "y3", "y4", "y5", "y8"]].mean(axis=1)
preds

,id,y,y2,y3,y4,y5,y6,y7,y8
0,0.0,68.726470,71.533780,68.609024,68.030537,68.889216,67.068665,70.047874,69.377102
1,1.0,68.868497,72.851500,71.004486,69.829855,69.524314,70.423965,73.610070,65.115333
2,2.0,69.951472,68.040250,70.915270,68.810176,69.944657,68.458860,71.614784,70.135785
3,3.0,69.550044,68.064420,69.418610,69.750191,70.334325,66.851555,67.958290,68.697049
4,4.0,69.611078,68.933790,68.105770,69.803567,70.356628,69.502220,71.232490,70.178348
...,...,...,...,...,...,...,...,...,...
771,771.0,54.817105,58.097153,51.779766,57.426455,56.660079,55.126860,59.951912,53.402120
772,772.0,72.278439,76.757370,76.359350,71.783131,70.838657,74.755310,74.027250,70.132616
773,773.0,74.549648,75.966230,75.667590,74.813400,76.045280,73.221650,75.620750,71.672322
774,774.0,72.806356,79.217420,78.190186,67.961404,68.560612,74.681015,73.699470,76.513223
775,775.0,72.478413,74.744940,73.499570,71.855750,73.175436,75.865070,77.591360,71.382895

In [29]:
preds = preds[["id", "y"]]
preds

        id          y
0      0.0  68.726470
1      1.0  68.868497
2      2.0  69.951472
3      3.0  69.550044
4      4.0  69.611078
..     ...        ...
771  771.0  54.817105
772  772.0  72.278439
773  773.0  74.549648
774  774.0  72.806356
775  775.0  72.478413

[776 rows x 2 columns]

In [30]:
preds.to_csv("predictions.csv", index=False)